"""ORM models for the six tables the Java backend's JPA entities describe.

Column names follow Hibernate's ``CamelCaseToUnderscoresNamingStrategy``, which
inserts ``_`` only where a lowercase char is followed by an uppercase then a
lowercase - hence ``p1elo_change`` and not ``p1_elo_change``. FastAPI owns the
schema now, but the names are kept so ``legacy/`` stays usable against the same
database. Where a Hibernate name is awkward, a clean Python attribute is mapped
onto it rather than renaming the column.
"""

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    ForeignKey,
    Identity,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import relationship

from app.database import Base


def _id_column() -> Column:
    """Hibernate's ``GenerationType.IDENTITY`` on PostgreSQL renders
    ``bigint generated by default as identity``, not ``bigserial``.
    """
    return Column(BigInteger, Identity(), primary_key=True)


class User(Base):
    __tablename__ = "users"

    id = _id_column()
    name = Column(String(255))
    # No unique constraint on username: the Java app never had one, so
    # registration can create duplicates and login looks up by username.
    # Preserved deliberately rather than silently tightened.
    username = Column(String(255))
    email = Column(String(255), unique=True)
    elo = Column(Integer, nullable=False)
    encrypted_password = Column(String(255))
    is_guest = Column(Boolean, nullable=False, default=False)
    is_admin = Column(
        Boolean, nullable=False, server_default=text("false"), default=False
    )
    created_at = Column(TIMESTAMP(precision=6))


class Problem(Base):
    __tablename__ = "problems"

    id = _id_column()
    title = Column(String(255))
    description = Column(Text)
    input_format = Column(Text)
    output_format = Column(Text)
    constraints = Column(Text)
    difficulty = Column(String(255))
    rating = Column(Integer, nullable=False)
    avg_solving_time = Column(Integer, nullable=False)

    # The @NotBlank annotations on five of the columns above do not become
    # NOT NULL: Hibernate's DDL export honours @NotNull only, so validation
    # stays in the application layer.

    test_cases = relationship(
        "TestCase",
        back_populates="problem",
        cascade="all, delete-orphan",
        lazy="selectin",
    )


class TestCase(Base):
    __tablename__ = "test_cases"

    id = _id_column()
    problem_id = Column(BigInteger, ForeignKey("problems.id"))
    input = Column(Text)
    expected_output = Column(Text)
    is_sample = Column(Boolean, nullable=False, default=False)

    problem = relationship("Problem", back_populates="test_cases")


class Match(Base):
    __tablename__ = "matches"

    # No foreign keys: the Java entity uses plain Long fields, not @ManyToOne.
    id = _id_column()
    p1 = Column(BigInteger)
    p2 = Column(BigInteger)
    problem_id = Column(BigInteger)
    # NULL = in progress, -1 = draw/abandoned, otherwise the winning user id.
    winner = Column(BigInteger)
    p1_elo_change = Column("p1elo_change", Integer, nullable=False, default=0)
    p2_elo_change = Column("p2elo_change", Integer, nullable=False, default=0)


class SolvedProblem(Base):
    __tablename__ = "solved_problems"

    # No foreign keys, same reason as `matches`.
    id = _id_column()
    user_id = Column(BigInteger)
    problem_id = Column(BigInteger)
    solved_at = Column(TIMESTAMP(precision=6))


class Visit(Base):
    # The Java entity carries no @Table, so Hibernate names it in the singular.
    __tablename__ = "visit"

    id = _id_column()
    count = Column(Integer, nullable=False)
